### ISSUE TITLE
update documentation to provide command line examples

### ISSUE THREAD

**Issue by IanMulvany** [JATS4R/validation#4]
I'm showing my relative ignorance here, as I'm very new to XSLT, I don't know how to run a validation. 

From the documentation available at this blog post: http://blog.eight02.com/2011/05/validating-xml-with-iso-schematron-on.html I downloaded `saxon9he.jar` and then tried to run the following command:

➜  validation git:(master) ✗ java -jar saxon9he.jar -o:output.xsl -s:jats4r-errlevel-0.sch
No stylesheet file name

I freely admit that i don't know what I'm doing here, so perhaps some command line examples might help people like me?

**Comment by Klortho** [comment]
@IanMulvany , I did some work to automate a lot of things, and include library dependencies into this repo.  The README file now has detailed usage instructions, starting with "Setup" and then "Validating a JATS file".  If you get a chance to try it, let us know if you run into any snags.
